/********************************************************************************
** Form generated from reading UI file 'pclvisualizer.ui'
**
** Created by: Qt User Interface Compiler version 5.5.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_PCLVISUALIZER_H
#define UI_PCLVISUALIZER_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDockWidget>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QWidget>
#include "QVTKWidget.h"

QT_BEGIN_NAMESPACE

class Ui_PCLVisualizerClass
{
public:
    QAction *actionOpen;
    QAction *actionExit;
    QAction *actionRemove;
    QAction *actionCovert;
    QAction *actionPx;
    QAction *actionPy;
    QAction *actionPz;
    QAction *actionSave;
    QAction *actionOpencloud;
    QAction *actionOpen_source_pcd;
    QAction *actionOpen_target_pcd;
    QAction *actionDisplay;
    QAction *toolaction;
    QAction *propertyaction;
    QAction *consoleaction;
    QAction *actionFrontView;
    QAction *actionLeftView;
    QAction *actionTopView;
    QAction *actionRightView;
    QAction *actionBottomView;
    QAction *actionBackView;
    QAction *actionBackgroundColor;
    QAction *actionCube;
    QAction *actionSphere;
    QAction *actionCylider;
    QWidget *centralWidget;
    QGridLayout *gridLayout;
    QVTKWidget *qvtkWidget;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuOpen_pcd_registration;
    QMenu *menuPassthrough;
    QMenu *menuCloudViewer;
    QMenu *menuView_2;
    QMenu *menuDisplay;
    QMenu *menuAngle_View;
    QMenu *menuGeometry;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;
    QDockWidget *PropertyDock;
    QWidget *dockWidgetContents;
    QGridLayout *gridLayout_2;
    QTableWidget *tableWidget;
    QDockWidget *ConsoleDock;
    QWidget *dockWidgetContents_2;
    QGridLayout *gridLayout_3;
    QTableWidget *consoleTable;
    QDockWidget *ToolDock;
    QWidget *dockWidgetContents_3;
    QToolBox *toolBox;
    QWidget *page_8;
    QGroupBox *groupBox_17;
    QLabel *label_setLeafSize_X_3;
    QLineEdit *lineEdit_Transform_X;
    QLabel *label_setLeafSize_X_4;
    QLineEdit *lineEdit_Transform_Y;
    QLabel *label_setLeafSize_X_5;
    QLineEdit *lineEdit_Transform_Z;
    QPushButton *buttonoutlier_3;
    QGroupBox *groupBox_18;
    QRadioButton *radioButton_Translation_X;
    QRadioButton *radioButton_Translation_Z;
    QRadioButton *radioButton_Translation_Y;
    QLineEdit *lineEdit_Translation_Degree;
    QLabel *label_7;
    QWidget *page_3;
    QGroupBox *groupBox_5;
    QLineEdit *lineEdit_Outlier_threshold;
    QLineEdit *lineEdit_Outlier_neibor;
    QLabel *label_Outlier_neibor;
    QLabel *label_Outlier_neibor_2;
    QPushButton *buttonoutlier;
    QWidget *page;
    QGroupBox *groupBox_3;
    QLineEdit *lineEdit_VoxelGrid_Y;
    QLineEdit *lineEdit_VoxelGrid_Z;
    QLineEdit *lineEdit_VoxelGrid_X;
    QLabel *label_setLeafSize_X;
    QLabel *label_setLeafSize_Z;
    QLabel *label_setLeafSize_Y;
    QPushButton *buttonvoxelgrid;
    QWidget *Greedy_Projection;
    QGroupBox *groupBox_6;
    QLineEdit *lineEdit_Greedy_MaxNear;
    QLineEdit *lineEdit_Greedy_Ksearch;
    QLineEdit *lineEdit_Greedy_SearchRadius;
    QLineEdit *lineEdit_Greedy_MaxAngle;
    QLineEdit *lineEdit_Greedy_MaxSurfaceaAngle;
    QLineEdit *lineEdit_Greedy_MinAngle;
    QPushButton *buttonoutlier_2;
    QLabel *label_Greedy_Ksearch;
    QLabel *label_Greedy_Maxnear;
    QLabel *label_Greedy_SearchRadius;
    QLabel *label_Greedy_TriangleAngle;
    QLabel *label_Greedy_Minangle;
    QLabel *label_Greedy_Maxangle;
    QLabel *label_Greedy_MaxSurfaceangle;
    QWidget *page_2;
    QGroupBox *groupBox;
    QPushButton *buttonpasstrough;
    QRadioButton *radioButton_FilterLimitsNegative;
    QGroupBox *groupBox_2;
    QRadioButton *radioButton_FilterFieldName_X;
    QRadioButton *radioButton_FilterFieldName_Z;
    QRadioButton *radioButton_FilterFieldName_Y;
    QGroupBox *groupBox_4;
    QLineEdit *lineEdit_FilterLimits_to;
    QLineEdit *lineEdit_FilterLimits_from;
    QLabel *label;
    QLabel *label_2;
    QWidget *page_4;
    QGroupBox *groupBox_7;
    QGroupBox *groupBox_9;
    QRadioButton *radioButton_SegmentationFilter_X;
    QRadioButton *radioButton_SegmentationFilter_Z;
    QRadioButton *radioButton_SegmentationFilter_Y;
    QGroupBox *groupBox_10;
    QLineEdit *lineEdit_SegmentationFilter_to;
    QLineEdit *lineEdit_SegmentationFilter_from;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_Greedy_Maxnear_2;
    QLineEdit *lineEdit_Segmentation_Distancethreshold;
    QLabel *label_Greedy_Maxnear_3;
    QLineEdit *lineEdit_Segmentation_MaxIterations;
    QPushButton *buttonpsegmentation;
    QWidget *page_5;
    QGroupBox *groupBox_8;
    QGroupBox *groupBox_11;
    QRadioButton *radioButton_SegmentationCyliderFilter_X;
    QRadioButton *radioButton_SegmentationCyliderFilter_Z;
    QRadioButton *radioButton_SegmentationCyliderFilter_Y;
    QGroupBox *groupBox_12;
    QLineEdit *lineEdit_SegmentationCyliderFilter_to;
    QLineEdit *lineEdit_SegmentationCyliderFilter_from;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_Greedy_Maxnear_4;
    QLabel *label_Greedy_Maxnear_5;
    QLineEdit *lineEdit_SegmentationCylider_Distancethreshold;
    QPushButton *buttonpsegmentation_2;
    QLineEdit *lineEdit_SegmentationCylider_MaxIterations_2;
    QLineEdit *lineEdit_SegmentationCylider_Radiuslimits;
    QLabel *label_Greedy_Maxnear_6;
    QWidget *page_7;
    QGroupBox *groupBox_14;
    QPushButton *buttonndt;
    QGroupBox *groupBox_15;
    QLineEdit *lineEdit_NormalDisTrans_Stepsize;
    QLabel *label_Greedy_Maxnear_9;
    QLineEdit *lineEdit_NormalDisTrans_Maxiterations;
    QLabel *label_Greedy_Maxnear_8;
    QLineEdit *lineEdit_NormalDisTrans_Gridresolution;
    QLabel *label_Greedy_Maxnear_10;
    QLineEdit *lineEdit_NormalDisTrans_Transepsilon;
    QLabel *label_Greedy_Maxnear_7;
    QGroupBox *groupBox_16;
    QLineEdit *lineEdit_VoxelGridNDT_X;
    QLabel *label_setLeafSize_Z_2;
    QLabel *label_setLeafSize_Y_2;
    QLabel *label_setLeafSize_X_2;
    QLineEdit *lineEdit_VoxelGridNDT_Y;
    QLineEdit *lineEdit_VoxelGridNDT_Z;
    QWidget *page_6;
    QGroupBox *groupBox_13;
    QLabel *label_Greedy_Maxnear_11;
    QLineEdit *lineEdit_ICP_Maxiterations;
    QPushButton *buttonicp;
    QLabel *label_Greedy_Maxnear_12;
    QLineEdit *lineEdit_ICP_Epsilon;
    QLabel *label_8;

    void setupUi(QMainWindow *PCLVisualizerClass)
    {
        if (PCLVisualizerClass->objectName().isEmpty())
            PCLVisualizerClass->setObjectName(QStringLiteral("PCLVisualizerClass"));
        PCLVisualizerClass->resize(1068, 701);
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(PCLVisualizerClass->sizePolicy().hasHeightForWidth());
        PCLVisualizerClass->setSizePolicy(sizePolicy);
        PCLVisualizerClass->setFocusPolicy(Qt::StrongFocus);
        PCLVisualizerClass->setAcceptDrops(true);
        actionOpen = new QAction(PCLVisualizerClass);
        actionOpen->setObjectName(QStringLiteral("actionOpen"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/Resources/images/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen->setIcon(icon);
        actionOpen->setIconVisibleInMenu(true);
        actionExit = new QAction(PCLVisualizerClass);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/Resources/images/exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExit->setIcon(icon1);
        actionRemove = new QAction(PCLVisualizerClass);
        actionRemove->setObjectName(QStringLiteral("actionRemove"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/Resources/images/remove.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRemove->setIcon(icon2);
        actionCovert = new QAction(PCLVisualizerClass);
        actionCovert->setObjectName(QStringLiteral("actionCovert"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/Resources/images/txt2pcd.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCovert->setIcon(icon3);
        actionPx = new QAction(PCLVisualizerClass);
        actionPx->setObjectName(QStringLiteral("actionPx"));
        actionPy = new QAction(PCLVisualizerClass);
        actionPy->setObjectName(QStringLiteral("actionPy"));
        actionPz = new QAction(PCLVisualizerClass);
        actionPz->setObjectName(QStringLiteral("actionPz"));
        actionSave = new QAction(PCLVisualizerClass);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/Resources/images/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave->setIcon(icon4);
        actionOpencloud = new QAction(PCLVisualizerClass);
        actionOpencloud->setObjectName(QStringLiteral("actionOpencloud"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/Resources/images/opencloud.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpencloud->setIcon(icon5);
        actionOpen_source_pcd = new QAction(PCLVisualizerClass);
        actionOpen_source_pcd->setObjectName(QStringLiteral("actionOpen_source_pcd"));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/Resources/images/cloudsource.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen_source_pcd->setIcon(icon6);
        actionOpen_target_pcd = new QAction(PCLVisualizerClass);
        actionOpen_target_pcd->setObjectName(QStringLiteral("actionOpen_target_pcd"));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/Resources/images/cloudtarget.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen_target_pcd->setIcon(icon7);
        actionDisplay = new QAction(PCLVisualizerClass);
        actionDisplay->setObjectName(QStringLiteral("actionDisplay"));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/Resources/images/eye.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionDisplay->setIcon(icon8);
        toolaction = new QAction(PCLVisualizerClass);
        toolaction->setObjectName(QStringLiteral("toolaction"));
        toolaction->setCheckable(true);
        toolaction->setChecked(true);
        propertyaction = new QAction(PCLVisualizerClass);
        propertyaction->setObjectName(QStringLiteral("propertyaction"));
        propertyaction->setCheckable(true);
        propertyaction->setChecked(true);
        consoleaction = new QAction(PCLVisualizerClass);
        consoleaction->setObjectName(QStringLiteral("consoleaction"));
        consoleaction->setCheckable(true);
        consoleaction->setChecked(true);
        actionFrontView = new QAction(PCLVisualizerClass);
        actionFrontView->setObjectName(QStringLiteral("actionFrontView"));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/Resources/images/front_view.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFrontView->setIcon(icon9);
        actionLeftView = new QAction(PCLVisualizerClass);
        actionLeftView->setObjectName(QStringLiteral("actionLeftView"));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/Resources/images/left_view.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLeftView->setIcon(icon10);
        actionTopView = new QAction(PCLVisualizerClass);
        actionTopView->setObjectName(QStringLiteral("actionTopView"));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/Resources/images/top_view.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionTopView->setIcon(icon11);
        actionRightView = new QAction(PCLVisualizerClass);
        actionRightView->setObjectName(QStringLiteral("actionRightView"));
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/Resources/images/right_view.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionRightView->setIcon(icon12);
        actionBottomView = new QAction(PCLVisualizerClass);
        actionBottomView->setObjectName(QStringLiteral("actionBottomView"));
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/Resources/images/bottom_view.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBottomView->setIcon(icon13);
        actionBackView = new QAction(PCLVisualizerClass);
        actionBackView->setObjectName(QStringLiteral("actionBackView"));
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/Resources/images/back_view.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBackView->setIcon(icon14);
        actionBackgroundColor = new QAction(PCLVisualizerClass);
        actionBackgroundColor->setObjectName(QStringLiteral("actionBackgroundColor"));
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/Resources/images/bgcolor.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionBackgroundColor->setIcon(icon15);
        actionCube = new QAction(PCLVisualizerClass);
        actionCube->setObjectName(QStringLiteral("actionCube"));
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/Resources/images/cube.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCube->setIcon(icon16);
        actionSphere = new QAction(PCLVisualizerClass);
        actionSphere->setObjectName(QStringLiteral("actionSphere"));
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/Resources/images/sphere.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSphere->setIcon(icon17);
        actionCylider = new QAction(PCLVisualizerClass);
        actionCylider->setObjectName(QStringLiteral("actionCylider"));
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/Resources/images/cylinder.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCylider->setIcon(icon18);
        centralWidget = new QWidget(PCLVisualizerClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        gridLayout = new QGridLayout(centralWidget);
        gridLayout->setSpacing(6);
        gridLayout->setContentsMargins(11, 11, 11, 11);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        qvtkWidget = new QVTKWidget(centralWidget);
        qvtkWidget->setObjectName(QStringLiteral("qvtkWidget"));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(qvtkWidget->sizePolicy().hasHeightForWidth());
        qvtkWidget->setSizePolicy(sizePolicy1);
        qvtkWidget->setAutoFillBackground(true);

        gridLayout->addWidget(qvtkWidget, 0, 0, 1, 1);

        PCLVisualizerClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(PCLVisualizerClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1068, 23));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuOpen_pcd_registration = new QMenu(menuFile);
        menuOpen_pcd_registration->setObjectName(QStringLiteral("menuOpen_pcd_registration"));
        menuPassthrough = new QMenu(menuBar);
        menuPassthrough->setObjectName(QStringLiteral("menuPassthrough"));
        menuCloudViewer = new QMenu(menuBar);
        menuCloudViewer->setObjectName(QStringLiteral("menuCloudViewer"));
        menuView_2 = new QMenu(menuBar);
        menuView_2->setObjectName(QStringLiteral("menuView_2"));
        menuDisplay = new QMenu(menuBar);
        menuDisplay->setObjectName(QStringLiteral("menuDisplay"));
        menuAngle_View = new QMenu(menuDisplay);
        menuAngle_View->setObjectName(QStringLiteral("menuAngle_View"));
        menuGeometry = new QMenu(menuBar);
        menuGeometry->setObjectName(QStringLiteral("menuGeometry"));
        PCLVisualizerClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(PCLVisualizerClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        PCLVisualizerClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(PCLVisualizerClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        PCLVisualizerClass->setStatusBar(statusBar);
        PropertyDock = new QDockWidget(PCLVisualizerClass);
        PropertyDock->setObjectName(QStringLiteral("PropertyDock"));
        PropertyDock->setEnabled(true);
        PropertyDock->setMinimumSize(QSize(200, 111));
        dockWidgetContents = new QWidget();
        dockWidgetContents->setObjectName(QStringLiteral("dockWidgetContents"));
        gridLayout_2 = new QGridLayout(dockWidgetContents);
        gridLayout_2->setSpacing(6);
        gridLayout_2->setContentsMargins(11, 11, 11, 11);
        gridLayout_2->setObjectName(QStringLiteral("gridLayout_2"));
        tableWidget = new QTableWidget(dockWidgetContents);
        if (tableWidget->columnCount() < 2)
            tableWidget->setColumnCount(2);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        if (tableWidget->rowCount() < 4)
            tableWidget->setRowCount(4);
        tableWidget->setObjectName(QStringLiteral("tableWidget"));
        tableWidget->setAutoScroll(true);
        tableWidget->setShowGrid(true);
        tableWidget->setGridStyle(Qt::DashDotDotLine);
        tableWidget->setWordWrap(true);
        tableWidget->setCornerButtonEnabled(true);
        tableWidget->setRowCount(4);

        gridLayout_2->addWidget(tableWidget, 0, 0, 1, 1);

        PropertyDock->setWidget(dockWidgetContents);
        PCLVisualizerClass->addDockWidget(static_cast<Qt::DockWidgetArea>(1), PropertyDock);
        ConsoleDock = new QDockWidget(PCLVisualizerClass);
        ConsoleDock->setObjectName(QStringLiteral("ConsoleDock"));
        ConsoleDock->setMinimumSize(QSize(274, 111));
        dockWidgetContents_2 = new QWidget();
        dockWidgetContents_2->setObjectName(QStringLiteral("dockWidgetContents_2"));
        gridLayout_3 = new QGridLayout(dockWidgetContents_2);
        gridLayout_3->setSpacing(6);
        gridLayout_3->setContentsMargins(11, 11, 11, 11);
        gridLayout_3->setObjectName(QStringLiteral("gridLayout_3"));
        consoleTable = new QTableWidget(dockWidgetContents_2);
        if (consoleTable->columnCount() < 3)
            consoleTable->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        consoleTable->setHorizontalHeaderItem(0, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        consoleTable->setHorizontalHeaderItem(1, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        consoleTable->setHorizontalHeaderItem(2, __qtablewidgetitem4);
        consoleTable->setObjectName(QStringLiteral("consoleTable"));
        consoleTable->setMinimumSize(QSize(256, 0));

        gridLayout_3->addWidget(consoleTable, 0, 0, 1, 1);

        ConsoleDock->setWidget(dockWidgetContents_2);
        PCLVisualizerClass->addDockWidget(static_cast<Qt::DockWidgetArea>(1), ConsoleDock);
        ToolDock = new QDockWidget(PCLVisualizerClass);
        ToolDock->setObjectName(QStringLiteral("ToolDock"));
        ToolDock->setMinimumSize(QSize(175, 38));
        dockWidgetContents_3 = new QWidget();
        dockWidgetContents_3->setObjectName(QStringLiteral("dockWidgetContents_3"));
        toolBox = new QToolBox(dockWidgetContents_3);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setGeometry(QRect(0, 0, 171, 541));
        QFont font;
        font.setStyleStrategy(QFont::PreferAntialias);
        toolBox->setFont(font);
        toolBox->setFrameShape(QFrame::NoFrame);
        toolBox->setFrameShadow(QFrame::Sunken);
        toolBox->setLineWidth(1);
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        page_8->setGeometry(QRect(0, 0, 171, 307));
        groupBox_17 = new QGroupBox(page_8);
        groupBox_17->setObjectName(QStringLiteral("groupBox_17"));
        groupBox_17->setGeometry(QRect(0, 0, 171, 241));
        label_setLeafSize_X_3 = new QLabel(groupBox_17);
        label_setLeafSize_X_3->setObjectName(QStringLiteral("label_setLeafSize_X_3"));
        label_setLeafSize_X_3->setGeometry(QRect(10, 30, 91, 16));
        lineEdit_Transform_X = new QLineEdit(groupBox_17);
        lineEdit_Transform_X->setObjectName(QStringLiteral("lineEdit_Transform_X"));
        lineEdit_Transform_X->setGeometry(QRect(110, 30, 40, 18));
        label_setLeafSize_X_4 = new QLabel(groupBox_17);
        label_setLeafSize_X_4->setObjectName(QStringLiteral("label_setLeafSize_X_4"));
        label_setLeafSize_X_4->setGeometry(QRect(10, 60, 91, 16));
        lineEdit_Transform_Y = new QLineEdit(groupBox_17);
        lineEdit_Transform_Y->setObjectName(QStringLiteral("lineEdit_Transform_Y"));
        lineEdit_Transform_Y->setGeometry(QRect(110, 60, 40, 18));
        label_setLeafSize_X_5 = new QLabel(groupBox_17);
        label_setLeafSize_X_5->setObjectName(QStringLiteral("label_setLeafSize_X_5"));
        label_setLeafSize_X_5->setGeometry(QRect(10, 90, 91, 16));
        lineEdit_Transform_Z = new QLineEdit(groupBox_17);
        lineEdit_Transform_Z->setObjectName(QStringLiteral("lineEdit_Transform_Z"));
        lineEdit_Transform_Z->setGeometry(QRect(110, 90, 40, 18));
        buttonoutlier_3 = new QPushButton(groupBox_17);
        buttonoutlier_3->setObjectName(QStringLiteral("buttonoutlier_3"));
        buttonoutlier_3->setGeometry(QRect(60, 210, 50, 20));
        QFont font1;
        font1.setBold(false);
        font1.setWeight(50);
        buttonoutlier_3->setFont(font1);
        groupBox_18 = new QGroupBox(groupBox_17);
        groupBox_18->setObjectName(QStringLiteral("groupBox_18"));
        groupBox_18->setGeometry(QRect(5, 116, 161, 51));
        groupBox_18->setFont(font1);
        radioButton_Translation_X = new QRadioButton(groupBox_18);
        radioButton_Translation_X->setObjectName(QStringLiteral("radioButton_Translation_X"));
        radioButton_Translation_X->setGeometry(QRect(16, 20, 31, 16));
        radioButton_Translation_X->setChecked(true);
        radioButton_Translation_Z = new QRadioButton(groupBox_18);
        radioButton_Translation_Z->setObjectName(QStringLiteral("radioButton_Translation_Z"));
        radioButton_Translation_Z->setGeometry(QRect(122, 20, 31, 16));
        radioButton_Translation_Y = new QRadioButton(groupBox_18);
        radioButton_Translation_Y->setObjectName(QStringLiteral("radioButton_Translation_Y"));
        radioButton_Translation_Y->setGeometry(QRect(72, 20, 31, 16));
        lineEdit_Translation_Degree = new QLineEdit(groupBox_17);
        lineEdit_Translation_Degree->setObjectName(QStringLiteral("lineEdit_Translation_Degree"));
        lineEdit_Translation_Degree->setGeometry(QRect(110, 170, 41, 18));
        label_7 = new QLabel(groupBox_17);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 170, 51, 16));
        toolBox->addItem(page_8, QStringLiteral("Matrix Transform"));
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        page_3->setGeometry(QRect(0, 0, 171, 307));
        groupBox_5 = new QGroupBox(page_3);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(0, 10, 160, 111));
        lineEdit_Outlier_threshold = new QLineEdit(groupBox_5);
        lineEdit_Outlier_threshold->setObjectName(QStringLiteral("lineEdit_Outlier_threshold"));
        lineEdit_Outlier_threshold->setGeometry(QRect(110, 50, 40, 18));
        lineEdit_Outlier_neibor = new QLineEdit(groupBox_5);
        lineEdit_Outlier_neibor->setObjectName(QStringLiteral("lineEdit_Outlier_neibor"));
        lineEdit_Outlier_neibor->setGeometry(QRect(110, 20, 40, 18));
        label_Outlier_neibor = new QLabel(groupBox_5);
        label_Outlier_neibor->setObjectName(QStringLiteral("label_Outlier_neibor"));
        label_Outlier_neibor->setGeometry(QRect(10, 20, 91, 16));
        label_Outlier_neibor_2 = new QLabel(groupBox_5);
        label_Outlier_neibor_2->setObjectName(QStringLiteral("label_Outlier_neibor_2"));
        label_Outlier_neibor_2->setGeometry(QRect(10, 50, 91, 16));
        buttonoutlier = new QPushButton(groupBox_5);
        buttonoutlier->setObjectName(QStringLiteral("buttonoutlier"));
        buttonoutlier->setGeometry(QRect(60, 80, 50, 20));
        buttonoutlier->setFont(font1);
        toolBox->addItem(page_3, QStringLiteral("Statistic Out Removal"));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        page->setGeometry(QRect(0, 0, 171, 307));
        groupBox_3 = new QGroupBox(page);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 0, 170, 141));
        groupBox_3->setMinimumSize(QSize(170, 0));
        groupBox_3->setMaximumSize(QSize(170, 16777215));
        lineEdit_VoxelGrid_Y = new QLineEdit(groupBox_3);
        lineEdit_VoxelGrid_Y->setObjectName(QStringLiteral("lineEdit_VoxelGrid_Y"));
        lineEdit_VoxelGrid_Y->setGeometry(QRect(110, 50, 40, 18));
        lineEdit_VoxelGrid_Z = new QLineEdit(groupBox_3);
        lineEdit_VoxelGrid_Z->setObjectName(QStringLiteral("lineEdit_VoxelGrid_Z"));
        lineEdit_VoxelGrid_Z->setGeometry(QRect(110, 80, 40, 18));
        lineEdit_VoxelGrid_X = new QLineEdit(groupBox_3);
        lineEdit_VoxelGrid_X->setObjectName(QStringLiteral("lineEdit_VoxelGrid_X"));
        lineEdit_VoxelGrid_X->setGeometry(QRect(110, 20, 40, 18));
        label_setLeafSize_X = new QLabel(groupBox_3);
        label_setLeafSize_X->setObjectName(QStringLiteral("label_setLeafSize_X"));
        label_setLeafSize_X->setGeometry(QRect(10, 20, 91, 16));
        label_setLeafSize_Z = new QLabel(groupBox_3);
        label_setLeafSize_Z->setObjectName(QStringLiteral("label_setLeafSize_Z"));
        label_setLeafSize_Z->setGeometry(QRect(10, 80, 91, 16));
        label_setLeafSize_Y = new QLabel(groupBox_3);
        label_setLeafSize_Y->setObjectName(QStringLiteral("label_setLeafSize_Y"));
        label_setLeafSize_Y->setGeometry(QRect(10, 50, 91, 16));
        buttonvoxelgrid = new QPushButton(groupBox_3);
        buttonvoxelgrid->setObjectName(QStringLiteral("buttonvoxelgrid"));
        buttonvoxelgrid->setGeometry(QRect(60, 105, 50, 20));
        buttonvoxelgrid->setFont(font1);
        toolBox->addItem(page, QStringLiteral("VoxelGrid Filter"));
        Greedy_Projection = new QWidget();
        Greedy_Projection->setObjectName(QStringLiteral("Greedy_Projection"));
        Greedy_Projection->setGeometry(QRect(0, 0, 171, 307));
        groupBox_6 = new QGroupBox(Greedy_Projection);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(0, 0, 170, 241));
        lineEdit_Greedy_MaxNear = new QLineEdit(groupBox_6);
        lineEdit_Greedy_MaxNear->setObjectName(QStringLiteral("lineEdit_Greedy_MaxNear"));
        lineEdit_Greedy_MaxNear->setGeometry(QRect(120, 48, 41, 18));
        lineEdit_Greedy_Ksearch = new QLineEdit(groupBox_6);
        lineEdit_Greedy_Ksearch->setObjectName(QStringLiteral("lineEdit_Greedy_Ksearch"));
        lineEdit_Greedy_Ksearch->setGeometry(QRect(120, 20, 41, 18));
        lineEdit_Greedy_SearchRadius = new QLineEdit(groupBox_6);
        lineEdit_Greedy_SearchRadius->setObjectName(QStringLiteral("lineEdit_Greedy_SearchRadius"));
        lineEdit_Greedy_SearchRadius->setGeometry(QRect(120, 80, 41, 18));
        lineEdit_Greedy_MaxAngle = new QLineEdit(groupBox_6);
        lineEdit_Greedy_MaxAngle->setObjectName(QStringLiteral("lineEdit_Greedy_MaxAngle"));
        lineEdit_Greedy_MaxAngle->setGeometry(QRect(120, 180, 41, 18));
        lineEdit_Greedy_MaxSurfaceaAngle = new QLineEdit(groupBox_6);
        lineEdit_Greedy_MaxSurfaceaAngle->setObjectName(QStringLiteral("lineEdit_Greedy_MaxSurfaceaAngle"));
        lineEdit_Greedy_MaxSurfaceaAngle->setGeometry(QRect(120, 140, 41, 18));
        lineEdit_Greedy_MinAngle = new QLineEdit(groupBox_6);
        lineEdit_Greedy_MinAngle->setObjectName(QStringLiteral("lineEdit_Greedy_MinAngle"));
        lineEdit_Greedy_MinAngle->setGeometry(QRect(40, 140, 41, 18));
        buttonoutlier_2 = new QPushButton(groupBox_6);
        buttonoutlier_2->setObjectName(QStringLiteral("buttonoutlier_2"));
        buttonoutlier_2->setGeometry(QRect(10, 210, 50, 20));
        buttonoutlier_2->setFont(font1);
        label_Greedy_Ksearch = new QLabel(groupBox_6);
        label_Greedy_Ksearch->setObjectName(QStringLiteral("label_Greedy_Ksearch"));
        label_Greedy_Ksearch->setGeometry(QRect(10, 20, 101, 16));
        label_Greedy_Maxnear = new QLabel(groupBox_6);
        label_Greedy_Maxnear->setObjectName(QStringLiteral("label_Greedy_Maxnear"));
        label_Greedy_Maxnear->setGeometry(QRect(10, 48, 101, 16));
        label_Greedy_SearchRadius = new QLabel(groupBox_6);
        label_Greedy_SearchRadius->setObjectName(QStringLiteral("label_Greedy_SearchRadius"));
        label_Greedy_SearchRadius->setGeometry(QRect(10, 80, 101, 16));
        label_Greedy_TriangleAngle = new QLabel(groupBox_6);
        label_Greedy_TriangleAngle->setObjectName(QStringLiteral("label_Greedy_TriangleAngle"));
        label_Greedy_TriangleAngle->setGeometry(QRect(10, 120, 151, 16));
        label_Greedy_Minangle = new QLabel(groupBox_6);
        label_Greedy_Minangle->setObjectName(QStringLiteral("label_Greedy_Minangle"));
        label_Greedy_Minangle->setGeometry(QRect(10, 140, 31, 16));
        label_Greedy_Maxangle = new QLabel(groupBox_6);
        label_Greedy_Maxangle->setObjectName(QStringLiteral("label_Greedy_Maxangle"));
        label_Greedy_Maxangle->setGeometry(QRect(90, 140, 31, 16));
        label_Greedy_MaxSurfaceangle = new QLabel(groupBox_6);
        label_Greedy_MaxSurfaceangle->setObjectName(QStringLiteral("label_Greedy_MaxSurfaceangle"));
        label_Greedy_MaxSurfaceangle->setGeometry(QRect(10, 180, 111, 16));
        toolBox->addItem(Greedy_Projection, QStringLiteral("Greedy_Projection"));
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        page_2->setGeometry(QRect(0, 0, 171, 307));
        groupBox = new QGroupBox(page_2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(0, 0, 171, 181));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        groupBox->setFont(font2);
        buttonpasstrough = new QPushButton(groupBox);
        buttonpasstrough->setObjectName(QStringLiteral("buttonpasstrough"));
        buttonpasstrough->setGeometry(QRect(105, 140, 50, 20));
        buttonpasstrough->setFont(font1);
        radioButton_FilterLimitsNegative = new QRadioButton(groupBox);
        radioButton_FilterLimitsNegative->setObjectName(QStringLiteral("radioButton_FilterLimitsNegative"));
        radioButton_FilterLimitsNegative->setGeometry(QRect(11, 140, 71, 16));
        radioButton_FilterLimitsNegative->setFont(font1);
        groupBox_2 = new QGroupBox(groupBox);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(6, 16, 161, 51));
        groupBox_2->setFont(font1);
        radioButton_FilterFieldName_X = new QRadioButton(groupBox_2);
        radioButton_FilterFieldName_X->setObjectName(QStringLiteral("radioButton_FilterFieldName_X"));
        radioButton_FilterFieldName_X->setGeometry(QRect(16, 20, 31, 16));
        radioButton_FilterFieldName_X->setChecked(true);
        radioButton_FilterFieldName_Z = new QRadioButton(groupBox_2);
        radioButton_FilterFieldName_Z->setObjectName(QStringLiteral("radioButton_FilterFieldName_Z"));
        radioButton_FilterFieldName_Z->setGeometry(QRect(122, 20, 31, 16));
        radioButton_FilterFieldName_Y = new QRadioButton(groupBox_2);
        radioButton_FilterFieldName_Y->setObjectName(QStringLiteral("radioButton_FilterFieldName_Y"));
        radioButton_FilterFieldName_Y->setGeometry(QRect(72, 20, 31, 16));
        groupBox_4 = new QGroupBox(groupBox);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(6, 70, 160, 51));
        groupBox_4->setFont(font1);
        lineEdit_FilterLimits_to = new QLineEdit(groupBox_4);
        lineEdit_FilterLimits_to->setObjectName(QStringLiteral("lineEdit_FilterLimits_to"));
        lineEdit_FilterLimits_to->setGeometry(QRect(110, 20, 41, 18));
        lineEdit_FilterLimits_from = new QLineEdit(groupBox_4);
        lineEdit_FilterLimits_from->setObjectName(QStringLiteral("lineEdit_FilterLimits_from"));
        lineEdit_FilterLimits_from->setGeometry(QRect(40, 20, 41, 18));
        label = new QLabel(groupBox_4);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 20, 31, 16));
        label_2 = new QLabel(groupBox_4);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(90, 20, 16, 16));
        toolBox->addItem(page_2, QStringLiteral("Passthrough Filter"));
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        page_4->setGeometry(QRect(0, 0, 171, 307));
        groupBox_7 = new QGroupBox(page_4);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(0, 0, 171, 201));
        groupBox_9 = new QGroupBox(groupBox_7);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(6, 20, 161, 41));
        groupBox_9->setFont(font1);
        radioButton_SegmentationFilter_X = new QRadioButton(groupBox_9);
        radioButton_SegmentationFilter_X->setObjectName(QStringLiteral("radioButton_SegmentationFilter_X"));
        radioButton_SegmentationFilter_X->setGeometry(QRect(16, 17, 31, 16));
        radioButton_SegmentationFilter_Z = new QRadioButton(groupBox_9);
        radioButton_SegmentationFilter_Z->setObjectName(QStringLiteral("radioButton_SegmentationFilter_Z"));
        radioButton_SegmentationFilter_Z->setGeometry(QRect(122, 17, 31, 16));
        radioButton_SegmentationFilter_Y = new QRadioButton(groupBox_9);
        radioButton_SegmentationFilter_Y->setObjectName(QStringLiteral("radioButton_SegmentationFilter_Y"));
        radioButton_SegmentationFilter_Y->setGeometry(QRect(72, 17, 31, 16));
        radioButton_SegmentationFilter_Y->setChecked(true);
        groupBox_10 = new QGroupBox(groupBox_7);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(6, 60, 160, 40));
        groupBox_10->setFont(font1);
        lineEdit_SegmentationFilter_to = new QLineEdit(groupBox_10);
        lineEdit_SegmentationFilter_to->setObjectName(QStringLiteral("lineEdit_SegmentationFilter_to"));
        lineEdit_SegmentationFilter_to->setGeometry(QRect(110, 14, 41, 18));
        lineEdit_SegmentationFilter_from = new QLineEdit(groupBox_10);
        lineEdit_SegmentationFilter_from->setObjectName(QStringLiteral("lineEdit_SegmentationFilter_from"));
        lineEdit_SegmentationFilter_from->setGeometry(QRect(40, 14, 41, 18));
        label_3 = new QLabel(groupBox_10);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 14, 31, 16));
        label_4 = new QLabel(groupBox_10);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(90, 14, 16, 16));
        label_Greedy_Maxnear_2 = new QLabel(groupBox_7);
        label_Greedy_Maxnear_2->setObjectName(QStringLiteral("label_Greedy_Maxnear_2"));
        label_Greedy_Maxnear_2->setGeometry(QRect(15, 110, 101, 16));
        lineEdit_Segmentation_Distancethreshold = new QLineEdit(groupBox_7);
        lineEdit_Segmentation_Distancethreshold->setObjectName(QStringLiteral("lineEdit_Segmentation_Distancethreshold"));
        lineEdit_Segmentation_Distancethreshold->setGeometry(QRect(117, 110, 41, 18));
        label_Greedy_Maxnear_3 = new QLabel(groupBox_7);
        label_Greedy_Maxnear_3->setObjectName(QStringLiteral("label_Greedy_Maxnear_3"));
        label_Greedy_Maxnear_3->setGeometry(QRect(16, 142, 101, 16));
        lineEdit_Segmentation_MaxIterations = new QLineEdit(groupBox_7);
        lineEdit_Segmentation_MaxIterations->setObjectName(QStringLiteral("lineEdit_Segmentation_MaxIterations"));
        lineEdit_Segmentation_MaxIterations->setGeometry(QRect(117, 142, 41, 18));
        buttonpsegmentation = new QPushButton(groupBox_7);
        buttonpsegmentation->setObjectName(QStringLiteral("buttonpsegmentation"));
        buttonpsegmentation->setGeometry(QRect(60, 170, 50, 20));
        buttonpsegmentation->setFont(font1);
        toolBox->addItem(page_4, QStringLiteral("Planar Segmentation"));
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        page_5->setGeometry(QRect(0, 0, 171, 307));
        groupBox_8 = new QGroupBox(page_5);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(0, 0, 170, 251));
        groupBox_11 = new QGroupBox(groupBox_8);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(5, 20, 161, 41));
        groupBox_11->setFont(font1);
        radioButton_SegmentationCyliderFilter_X = new QRadioButton(groupBox_11);
        radioButton_SegmentationCyliderFilter_X->setObjectName(QStringLiteral("radioButton_SegmentationCyliderFilter_X"));
        radioButton_SegmentationCyliderFilter_X->setGeometry(QRect(16, 17, 31, 16));
        radioButton_SegmentationCyliderFilter_Z = new QRadioButton(groupBox_11);
        radioButton_SegmentationCyliderFilter_Z->setObjectName(QStringLiteral("radioButton_SegmentationCyliderFilter_Z"));
        radioButton_SegmentationCyliderFilter_Z->setGeometry(QRect(122, 17, 31, 16));
        radioButton_SegmentationCyliderFilter_Z->setChecked(true);
        radioButton_SegmentationCyliderFilter_Y = new QRadioButton(groupBox_11);
        radioButton_SegmentationCyliderFilter_Y->setObjectName(QStringLiteral("radioButton_SegmentationCyliderFilter_Y"));
        radioButton_SegmentationCyliderFilter_Y->setGeometry(QRect(72, 17, 31, 16));
        groupBox_12 = new QGroupBox(groupBox_8);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(5, 70, 160, 40));
        groupBox_12->setFont(font1);
        lineEdit_SegmentationCyliderFilter_to = new QLineEdit(groupBox_12);
        lineEdit_SegmentationCyliderFilter_to->setObjectName(QStringLiteral("lineEdit_SegmentationCyliderFilter_to"));
        lineEdit_SegmentationCyliderFilter_to->setGeometry(QRect(110, 14, 41, 18));
        lineEdit_SegmentationCyliderFilter_from = new QLineEdit(groupBox_12);
        lineEdit_SegmentationCyliderFilter_from->setObjectName(QStringLiteral("lineEdit_SegmentationCyliderFilter_from"));
        lineEdit_SegmentationCyliderFilter_from->setGeometry(QRect(40, 14, 41, 18));
        label_5 = new QLabel(groupBox_12);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 14, 31, 16));
        label_6 = new QLabel(groupBox_12);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(90, 14, 16, 16));
        label_Greedy_Maxnear_4 = new QLabel(groupBox_8);
        label_Greedy_Maxnear_4->setObjectName(QStringLiteral("label_Greedy_Maxnear_4"));
        label_Greedy_Maxnear_4->setGeometry(QRect(14, 118, 101, 16));
        label_Greedy_Maxnear_5 = new QLabel(groupBox_8);
        label_Greedy_Maxnear_5->setObjectName(QStringLiteral("label_Greedy_Maxnear_5"));
        label_Greedy_Maxnear_5->setGeometry(QRect(14, 150, 101, 16));
        lineEdit_SegmentationCylider_Distancethreshold = new QLineEdit(groupBox_8);
        lineEdit_SegmentationCylider_Distancethreshold->setObjectName(QStringLiteral("lineEdit_SegmentationCylider_Distancethreshold"));
        lineEdit_SegmentationCylider_Distancethreshold->setGeometry(QRect(115, 118, 41, 18));
        buttonpsegmentation_2 = new QPushButton(groupBox_8);
        buttonpsegmentation_2->setObjectName(QStringLiteral("buttonpsegmentation_2"));
        buttonpsegmentation_2->setGeometry(QRect(60, 210, 50, 20));
        buttonpsegmentation_2->setFont(font1);
        lineEdit_SegmentationCylider_MaxIterations_2 = new QLineEdit(groupBox_8);
        lineEdit_SegmentationCylider_MaxIterations_2->setObjectName(QStringLiteral("lineEdit_SegmentationCylider_MaxIterations_2"));
        lineEdit_SegmentationCylider_MaxIterations_2->setGeometry(QRect(115, 150, 41, 18));
        lineEdit_SegmentationCylider_Radiuslimits = new QLineEdit(groupBox_8);
        lineEdit_SegmentationCylider_Radiuslimits->setObjectName(QStringLiteral("lineEdit_SegmentationCylider_Radiuslimits"));
        lineEdit_SegmentationCylider_Radiuslimits->setGeometry(QRect(115, 180, 41, 18));
        label_Greedy_Maxnear_6 = new QLabel(groupBox_8);
        label_Greedy_Maxnear_6->setObjectName(QStringLiteral("label_Greedy_Maxnear_6"));
        label_Greedy_Maxnear_6->setGeometry(QRect(15, 180, 101, 16));
        toolBox->addItem(page_5, QStringLiteral("Cylider Segmentation"));
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        page_7->setGeometry(QRect(0, 0, 171, 307));
        groupBox_14 = new QGroupBox(page_7);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(0, 0, 170, 321));
        buttonndt = new QPushButton(groupBox_14);
        buttonndt->setObjectName(QStringLiteral("buttonndt"));
        buttonndt->setGeometry(QRect(60, 290, 50, 20));
        buttonndt->setFont(font1);
        groupBox_15 = new QGroupBox(groupBox_14);
        groupBox_15->setObjectName(QStringLiteral("groupBox_15"));
        groupBox_15->setGeometry(QRect(5, 140, 161, 141));
        lineEdit_NormalDisTrans_Stepsize = new QLineEdit(groupBox_15);
        lineEdit_NormalDisTrans_Stepsize->setObjectName(QStringLiteral("lineEdit_NormalDisTrans_Stepsize"));
        lineEdit_NormalDisTrans_Stepsize->setGeometry(QRect(110, 50, 41, 18));
        label_Greedy_Maxnear_9 = new QLabel(groupBox_15);
        label_Greedy_Maxnear_9->setObjectName(QStringLiteral("label_Greedy_Maxnear_9"));
        label_Greedy_Maxnear_9->setGeometry(QRect(10, 80, 101, 16));
        lineEdit_NormalDisTrans_Maxiterations = new QLineEdit(groupBox_15);
        lineEdit_NormalDisTrans_Maxiterations->setObjectName(QStringLiteral("lineEdit_NormalDisTrans_Maxiterations"));
        lineEdit_NormalDisTrans_Maxiterations->setGeometry(QRect(110, 110, 41, 18));
        label_Greedy_Maxnear_8 = new QLabel(groupBox_15);
        label_Greedy_Maxnear_8->setObjectName(QStringLiteral("label_Greedy_Maxnear_8"));
        label_Greedy_Maxnear_8->setGeometry(QRect(10, 50, 101, 16));
        lineEdit_NormalDisTrans_Gridresolution = new QLineEdit(groupBox_15);
        lineEdit_NormalDisTrans_Gridresolution->setObjectName(QStringLiteral("lineEdit_NormalDisTrans_Gridresolution"));
        lineEdit_NormalDisTrans_Gridresolution->setGeometry(QRect(110, 80, 41, 18));
        label_Greedy_Maxnear_10 = new QLabel(groupBox_15);
        label_Greedy_Maxnear_10->setObjectName(QStringLiteral("label_Greedy_Maxnear_10"));
        label_Greedy_Maxnear_10->setGeometry(QRect(10, 110, 101, 16));
        lineEdit_NormalDisTrans_Transepsilon = new QLineEdit(groupBox_15);
        lineEdit_NormalDisTrans_Transepsilon->setObjectName(QStringLiteral("lineEdit_NormalDisTrans_Transepsilon"));
        lineEdit_NormalDisTrans_Transepsilon->setGeometry(QRect(110, 20, 41, 18));
        label_Greedy_Maxnear_7 = new QLabel(groupBox_15);
        label_Greedy_Maxnear_7->setObjectName(QStringLiteral("label_Greedy_Maxnear_7"));
        label_Greedy_Maxnear_7->setGeometry(QRect(10, 20, 101, 16));
        groupBox_16 = new QGroupBox(groupBox_14);
        groupBox_16->setObjectName(QStringLiteral("groupBox_16"));
        groupBox_16->setGeometry(QRect(5, 20, 161, 111));
        lineEdit_VoxelGridNDT_X = new QLineEdit(groupBox_16);
        lineEdit_VoxelGridNDT_X->setObjectName(QStringLiteral("lineEdit_VoxelGridNDT_X"));
        lineEdit_VoxelGridNDT_X->setGeometry(QRect(110, 20, 40, 18));
        lineEdit_VoxelGridNDT_X->setReadOnly(false);
        label_setLeafSize_Z_2 = new QLabel(groupBox_16);
        label_setLeafSize_Z_2->setObjectName(QStringLiteral("label_setLeafSize_Z_2"));
        label_setLeafSize_Z_2->setGeometry(QRect(10, 80, 91, 16));
        label_setLeafSize_Y_2 = new QLabel(groupBox_16);
        label_setLeafSize_Y_2->setObjectName(QStringLiteral("label_setLeafSize_Y_2"));
        label_setLeafSize_Y_2->setGeometry(QRect(10, 50, 91, 16));
        label_setLeafSize_X_2 = new QLabel(groupBox_16);
        label_setLeafSize_X_2->setObjectName(QStringLiteral("label_setLeafSize_X_2"));
        label_setLeafSize_X_2->setGeometry(QRect(10, 20, 91, 16));
        lineEdit_VoxelGridNDT_Y = new QLineEdit(groupBox_16);
        lineEdit_VoxelGridNDT_Y->setObjectName(QStringLiteral("lineEdit_VoxelGridNDT_Y"));
        lineEdit_VoxelGridNDT_Y->setGeometry(QRect(110, 50, 40, 18));
        lineEdit_VoxelGridNDT_Z = new QLineEdit(groupBox_16);
        lineEdit_VoxelGridNDT_Z->setObjectName(QStringLiteral("lineEdit_VoxelGridNDT_Z"));
        lineEdit_VoxelGridNDT_Z->setGeometry(QRect(110, 80, 40, 18));
        toolBox->addItem(page_7, QStringLiteral("Normal Distributions Trans"));
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        page_6->setGeometry(QRect(0, 0, 171, 307));
        groupBox_13 = new QGroupBox(page_6);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(0, 0, 171, 121));
        label_Greedy_Maxnear_11 = new QLabel(groupBox_13);
        label_Greedy_Maxnear_11->setObjectName(QStringLiteral("label_Greedy_Maxnear_11"));
        label_Greedy_Maxnear_11->setGeometry(QRect(10, 20, 101, 16));
        lineEdit_ICP_Maxiterations = new QLineEdit(groupBox_13);
        lineEdit_ICP_Maxiterations->setObjectName(QStringLiteral("lineEdit_ICP_Maxiterations"));
        lineEdit_ICP_Maxiterations->setGeometry(QRect(120, 20, 41, 18));
        buttonicp = new QPushButton(groupBox_13);
        buttonicp->setObjectName(QStringLiteral("buttonicp"));
        buttonicp->setGeometry(QRect(60, 80, 50, 20));
        buttonicp->setFont(font1);
        label_Greedy_Maxnear_12 = new QLabel(groupBox_13);
        label_Greedy_Maxnear_12->setObjectName(QStringLiteral("label_Greedy_Maxnear_12"));
        label_Greedy_Maxnear_12->setGeometry(QRect(10, 50, 101, 16));
        lineEdit_ICP_Epsilon = new QLineEdit(groupBox_13);
        lineEdit_ICP_Epsilon->setObjectName(QStringLiteral("lineEdit_ICP_Epsilon"));
        lineEdit_ICP_Epsilon->setGeometry(QRect(120, 50, 41, 18));
        toolBox->addItem(page_6, QStringLiteral("Iterative Closest Point"));
        label_8 = new QLabel(dockWidgetContents_3);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(0, 540, 171, 61));
        label_8->setPixmap(QPixmap(QString::fromUtf8(":/Resources/images/logo.png")));
        label_8->setScaledContents(true);
        ToolDock->setWidget(dockWidgetContents_3);
        PCLVisualizerClass->addDockWidget(static_cast<Qt::DockWidgetArea>(2), ToolDock);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuDisplay->menuAction());
        menuBar->addAction(menuGeometry->menuAction());
        menuBar->addAction(menuPassthrough->menuAction());
        menuBar->addAction(menuView_2->menuAction());
        menuBar->addAction(menuCloudViewer->menuAction());
        menuFile->addAction(actionOpen);
        menuFile->addAction(menuOpen_pcd_registration->menuAction());
        menuFile->addAction(actionSave);
        menuFile->addAction(actionCovert);
        menuFile->addAction(actionRemove);
        menuFile->addAction(actionExit);
        menuOpen_pcd_registration->addAction(actionOpen_source_pcd);
        menuOpen_pcd_registration->addAction(actionOpen_target_pcd);
        menuOpen_pcd_registration->addAction(actionDisplay);
        menuPassthrough->addAction(actionPx);
        menuPassthrough->addAction(actionPy);
        menuPassthrough->addAction(actionPz);
        menuCloudViewer->addAction(actionOpencloud);
        menuView_2->addAction(toolaction);
        menuView_2->addAction(propertyaction);
        menuView_2->addAction(consoleaction);
        menuDisplay->addAction(menuAngle_View->menuAction());
        menuDisplay->addAction(actionBackgroundColor);
        menuAngle_View->addAction(actionFrontView);
        menuAngle_View->addAction(actionBackView);
        menuAngle_View->addAction(actionLeftView);
        menuAngle_View->addAction(actionRightView);
        menuAngle_View->addAction(actionTopView);
        menuAngle_View->addAction(actionBottomView);
        menuGeometry->addAction(actionCube);
        menuGeometry->addAction(actionSphere);
        menuGeometry->addAction(actionCylider);
        mainToolBar->addAction(actionOpen);
        mainToolBar->addAction(actionSave);
        mainToolBar->addAction(actionOpen_source_pcd);
        mainToolBar->addAction(actionOpen_target_pcd);
        mainToolBar->addAction(actionCovert);
        mainToolBar->addAction(actionRemove);
        mainToolBar->addAction(actionExit);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionFrontView);
        mainToolBar->addAction(actionBackView);
        mainToolBar->addAction(actionLeftView);
        mainToolBar->addAction(actionRightView);
        mainToolBar->addAction(actionTopView);
        mainToolBar->addAction(actionBottomView);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionBackgroundColor);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionCube);
        mainToolBar->addAction(actionSphere);
        mainToolBar->addAction(actionCylider);

        retranslateUi(PCLVisualizerClass);
        QObject::connect(buttonpasstrough, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onButtonPassthrough()));
        QObject::connect(buttonvoxelgrid, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onButtonVoxelGrid()));
        QObject::connect(buttonoutlier_2, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onButtonGreedyProjection()));
        QObject::connect(buttonoutlier, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onButtonOutlier()));
        QObject::connect(buttonpsegmentation, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onPlanarSegmentation()));
        QObject::connect(buttonpsegmentation_2, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onCyliderSegmentation()));
        QObject::connect(buttonndt, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onNormalDisTrans()));
        QObject::connect(buttonoutlier_3, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onTranslation()));
        QObject::connect(buttonicp, SIGNAL(clicked()), PCLVisualizerClass, SLOT(onIterativeClosestPoint()));

        toolBox->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(PCLVisualizerClass);
    } // setupUi

    void retranslateUi(QMainWindow *PCLVisualizerClass)
    {
        PCLVisualizerClass->setWindowTitle(QApplication::translate("PCLVisualizerClass", "PCLVisualizer", 0));
        actionOpen->setText(QApplication::translate("PCLVisualizerClass", "open pcd", 0));
        actionExit->setText(QApplication::translate("PCLVisualizerClass", "exit", 0));
        actionRemove->setText(QApplication::translate("PCLVisualizerClass", "remove", 0));
        actionCovert->setText(QApplication::translate("PCLVisualizerClass", "txt to pcd ", 0));
        actionPx->setText(QApplication::translate("PCLVisualizerClass", "P.x", 0));
        actionPy->setText(QApplication::translate("PCLVisualizerClass", "P.y", 0));
        actionPz->setText(QApplication::translate("PCLVisualizerClass", "P.z", 0));
        actionSave->setText(QApplication::translate("PCLVisualizerClass", "save pcd", 0));
        actionOpencloud->setText(QApplication::translate("PCLVisualizerClass", "open point cloud", 0));
        actionOpen_source_pcd->setText(QApplication::translate("PCLVisualizerClass", "open source pcd", 0));
        actionOpen_target_pcd->setText(QApplication::translate("PCLVisualizerClass", "open target pcd", 0));
        actionDisplay->setText(QApplication::translate("PCLVisualizerClass", "display", 0));
        toolaction->setText(QApplication::translate("PCLVisualizerClass", "Tool Dock", 0));
        propertyaction->setText(QApplication::translate("PCLVisualizerClass", "Property Dock", 0));
        consoleaction->setText(QApplication::translate("PCLVisualizerClass", "Console", 0));
        actionFrontView->setText(QApplication::translate("PCLVisualizerClass", "Set Front View", 0));
        actionLeftView->setText(QApplication::translate("PCLVisualizerClass", "Set Left View", 0));
        actionTopView->setText(QApplication::translate("PCLVisualizerClass", "Set Top View", 0));
        actionRightView->setText(QApplication::translate("PCLVisualizerClass", "Set Right View", 0));
        actionBottomView->setText(QApplication::translate("PCLVisualizerClass", "Set Bottom View", 0));
        actionBackView->setText(QApplication::translate("PCLVisualizerClass", "Set Back View", 0));
        actionBackgroundColor->setText(QApplication::translate("PCLVisualizerClass", "Background Color", 0));
        actionCube->setText(QApplication::translate("PCLVisualizerClass", "Cube", 0));
        actionSphere->setText(QApplication::translate("PCLVisualizerClass", "Sphere", 0));
        actionCylider->setText(QApplication::translate("PCLVisualizerClass", "Cylinder", 0));
        menuFile->setTitle(QApplication::translate("PCLVisualizerClass", "File", 0));
        menuOpen_pcd_registration->setTitle(QApplication::translate("PCLVisualizerClass", "open pcd registration", 0));
        menuPassthrough->setTitle(QApplication::translate("PCLVisualizerClass", "Passthrough", 0));
        menuCloudViewer->setTitle(QApplication::translate("PCLVisualizerClass", "CloudViewer", 0));
        menuView_2->setTitle(QApplication::translate("PCLVisualizerClass", "View", 0));
        menuDisplay->setTitle(QApplication::translate("PCLVisualizerClass", "Display", 0));
        menuAngle_View->setTitle(QApplication::translate("PCLVisualizerClass", "Angle View", 0));
        menuGeometry->setTitle(QApplication::translate("PCLVisualizerClass", "Geometry", 0));
        mainToolBar->setWindowTitle(QApplication::translate("PCLVisualizerClass", "ToolBar", 0));
        PropertyDock->setWindowTitle(QApplication::translate("PCLVisualizerClass", "Properties", 0));
        QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("PCLVisualizerClass", "Property", 0));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("PCLVisualizerClass", "Value", 0));
        ConsoleDock->setWindowTitle(QApplication::translate("PCLVisualizerClass", "Console", 0));
        QTableWidgetItem *___qtablewidgetitem2 = consoleTable->horizontalHeaderItem(0);
        ___qtablewidgetitem2->setText(QApplication::translate("PCLVisualizerClass", "Cloud", 0));
        QTableWidgetItem *___qtablewidgetitem3 = consoleTable->horizontalHeaderItem(1);
        ___qtablewidgetitem3->setText(QApplication::translate("PCLVisualizerClass", "Operation", 0));
        QTableWidgetItem *___qtablewidgetitem4 = consoleTable->horizontalHeaderItem(2);
        ___qtablewidgetitem4->setText(QApplication::translate("PCLVisualizerClass", "Details", 0));
        ToolDock->setWindowTitle(QApplication::translate("PCLVisualizerClass", "Processing algorithm", 0));
        groupBox_17->setTitle(QApplication::translate("PCLVisualizerClass", "Transform", 0));
        label_setLeafSize_X_3->setText(QApplication::translate("PCLVisualizerClass", "Translation_X", 0));
        lineEdit_Transform_X->setText(QApplication::translate("PCLVisualizerClass", "0.0", 0));
        label_setLeafSize_X_4->setText(QApplication::translate("PCLVisualizerClass", "Translation_Y", 0));
        lineEdit_Transform_Y->setText(QApplication::translate("PCLVisualizerClass", "0.0", 0));
        label_setLeafSize_X_5->setText(QApplication::translate("PCLVisualizerClass", "Translation_Z", 0));
        lineEdit_Transform_Z->setText(QApplication::translate("PCLVisualizerClass", "0.0", 0));
        buttonoutlier_3->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        groupBox_18->setTitle(QApplication::translate("PCLVisualizerClass", "Field", 0));
        radioButton_Translation_X->setText(QApplication::translate("PCLVisualizerClass", "X", 0));
        radioButton_Translation_Z->setText(QApplication::translate("PCLVisualizerClass", "Z", 0));
        radioButton_Translation_Y->setText(QApplication::translate("PCLVisualizerClass", "Y", 0));
        lineEdit_Translation_Degree->setText(QApplication::translate("PCLVisualizerClass", "60", 0));
        label_7->setText(QApplication::translate("PCLVisualizerClass", "Degree:", 0));
        toolBox->setItemText(toolBox->indexOf(page_8), QApplication::translate("PCLVisualizerClass", "Matrix Transform", 0));
        groupBox_5->setTitle(QApplication::translate("PCLVisualizerClass", "OutlierRemoval", 0));
        lineEdit_Outlier_threshold->setText(QApplication::translate("PCLVisualizerClass", "1.0", 0));
        lineEdit_Outlier_neibor->setText(QApplication::translate("PCLVisualizerClass", "50", 0));
        label_Outlier_neibor->setText(QApplication::translate("PCLVisualizerClass", "neighbor_num:", 0));
        label_Outlier_neibor_2->setText(QApplication::translate("PCLVisualizerClass", "threshold:", 0));
        buttonoutlier->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        toolBox->setItemText(toolBox->indexOf(page_3), QApplication::translate("PCLVisualizerClass", "Statistic Out Removal", 0));
        groupBox_3->setTitle(QApplication::translate("PCLVisualizerClass", "VoxelGrid", 0));
        lineEdit_VoxelGrid_Y->setText(QApplication::translate("PCLVisualizerClass", "0.2", 0));
        lineEdit_VoxelGrid_Z->setText(QApplication::translate("PCLVisualizerClass", "0.2", 0));
        lineEdit_VoxelGrid_X->setText(QApplication::translate("PCLVisualizerClass", "0.2", 0));
        label_setLeafSize_X->setText(QApplication::translate("PCLVisualizerClass", "setLeafSize_X:", 0));
        label_setLeafSize_Z->setText(QApplication::translate("PCLVisualizerClass", "setLeafSize_Z:", 0));
        label_setLeafSize_Y->setText(QApplication::translate("PCLVisualizerClass", "setLeafSize_Y:", 0));
        buttonvoxelgrid->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        toolBox->setItemText(toolBox->indexOf(page), QApplication::translate("PCLVisualizerClass", "VoxelGrid Filter", 0));
        groupBox_6->setTitle(QApplication::translate("PCLVisualizerClass", "Triangulation", 0));
        lineEdit_Greedy_MaxNear->setText(QApplication::translate("PCLVisualizerClass", "100", 0));
        lineEdit_Greedy_Ksearch->setText(QApplication::translate("PCLVisualizerClass", "20", 0));
        lineEdit_Greedy_SearchRadius->setText(QApplication::translate("PCLVisualizerClass", "0.025", 0));
        lineEdit_Greedy_MaxAngle->setText(QApplication::translate("PCLVisualizerClass", "45", 0));
        lineEdit_Greedy_MaxSurfaceaAngle->setText(QApplication::translate("PCLVisualizerClass", "120", 0));
        lineEdit_Greedy_MinAngle->setText(QApplication::translate("PCLVisualizerClass", "10", 0));
        buttonoutlier_2->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        label_Greedy_Ksearch->setText(QApplication::translate("PCLVisualizerClass", "K_search:(10-50)", 0));
        label_Greedy_Maxnear->setText(QApplication::translate("PCLVisualizerClass", "Maximum Near:", 0));
        label_Greedy_SearchRadius->setText(QApplication::translate("PCLVisualizerClass", "SearchRadius:", 0));
        label_Greedy_TriangleAngle->setText(QApplication::translate("PCLVisualizerClass", "Triangle Angle Limits;", 0));
        label_Greedy_Minangle->setText(QApplication::translate("PCLVisualizerClass", "MIN:", 0));
        label_Greedy_Maxangle->setText(QApplication::translate("PCLVisualizerClass", "MAX:", 0));
        label_Greedy_MaxSurfaceangle->setText(QApplication::translate("PCLVisualizerClass", "Max Surface Angle:", 0));
        toolBox->setItemText(toolBox->indexOf(Greedy_Projection), QApplication::translate("PCLVisualizerClass", "Greedy_Projection", 0));
        groupBox->setTitle(QApplication::translate("PCLVisualizerClass", "Passthrough", 0));
        buttonpasstrough->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        radioButton_FilterLimitsNegative->setText(QApplication::translate("PCLVisualizerClass", "Negative", 0));
        groupBox_2->setTitle(QApplication::translate("PCLVisualizerClass", "Field", 0));
        radioButton_FilterFieldName_X->setText(QApplication::translate("PCLVisualizerClass", "X", 0));
        radioButton_FilterFieldName_Z->setText(QApplication::translate("PCLVisualizerClass", "Z", 0));
        radioButton_FilterFieldName_Y->setText(QApplication::translate("PCLVisualizerClass", "Y", 0));
        groupBox_4->setTitle(QApplication::translate("PCLVisualizerClass", "Limits", 0));
        lineEdit_FilterLimits_to->setText(QApplication::translate("PCLVisualizerClass", "0.01", 0));
        lineEdit_FilterLimits_from->setText(QApplication::translate("PCLVisualizerClass", "-0.01", 0));
        label->setText(QApplication::translate("PCLVisualizerClass", "From", 0));
        label_2->setText(QApplication::translate("PCLVisualizerClass", "to", 0));
        toolBox->setItemText(toolBox->indexOf(page_2), QApplication::translate("PCLVisualizerClass", "Passthrough Filter", 0));
        groupBox_7->setTitle(QApplication::translate("PCLVisualizerClass", "PlaneExtraction", 0));
        groupBox_9->setTitle(QApplication::translate("PCLVisualizerClass", "Field", 0));
        radioButton_SegmentationFilter_X->setText(QApplication::translate("PCLVisualizerClass", "X", 0));
        radioButton_SegmentationFilter_Z->setText(QApplication::translate("PCLVisualizerClass", "Z", 0));
        radioButton_SegmentationFilter_Y->setText(QApplication::translate("PCLVisualizerClass", "Y", 0));
        groupBox_10->setTitle(QApplication::translate("PCLVisualizerClass", "Limits", 0));
        lineEdit_SegmentationFilter_to->setText(QApplication::translate("PCLVisualizerClass", "0.6", 0));
        lineEdit_SegmentationFilter_from->setText(QApplication::translate("PCLVisualizerClass", "-0.1", 0));
        label_3->setText(QApplication::translate("PCLVisualizerClass", "From", 0));
        label_4->setText(QApplication::translate("PCLVisualizerClass", "to", 0));
        label_Greedy_Maxnear_2->setText(QApplication::translate("PCLVisualizerClass", "Dis_threshold:", 0));
        lineEdit_Segmentation_Distancethreshold->setText(QApplication::translate("PCLVisualizerClass", "0.01", 0));
        label_Greedy_Maxnear_3->setText(QApplication::translate("PCLVisualizerClass", "Max iterations:", 0));
        lineEdit_Segmentation_MaxIterations->setText(QApplication::translate("PCLVisualizerClass", "100", 0));
        buttonpsegmentation->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        toolBox->setItemText(toolBox->indexOf(page_4), QApplication::translate("PCLVisualizerClass", "Planar Segmentation", 0));
        groupBox_8->setTitle(QApplication::translate("PCLVisualizerClass", "CyliderExtraction", 0));
        groupBox_11->setTitle(QApplication::translate("PCLVisualizerClass", "Field", 0));
        radioButton_SegmentationCyliderFilter_X->setText(QApplication::translate("PCLVisualizerClass", "X", 0));
        radioButton_SegmentationCyliderFilter_Z->setText(QApplication::translate("PCLVisualizerClass", "Z", 0));
        radioButton_SegmentationCyliderFilter_Y->setText(QApplication::translate("PCLVisualizerClass", "Y", 0));
        groupBox_12->setTitle(QApplication::translate("PCLVisualizerClass", "Limits", 0));
        lineEdit_SegmentationCyliderFilter_to->setText(QApplication::translate("PCLVisualizerClass", "1.5", 0));
        lineEdit_SegmentationCyliderFilter_from->setText(QApplication::translate("PCLVisualizerClass", "0", 0));
        label_5->setText(QApplication::translate("PCLVisualizerClass", "From", 0));
        label_6->setText(QApplication::translate("PCLVisualizerClass", "to", 0));
        label_Greedy_Maxnear_4->setText(QApplication::translate("PCLVisualizerClass", "Dis_threshold:", 0));
        label_Greedy_Maxnear_5->setText(QApplication::translate("PCLVisualizerClass", "Max iterations:", 0));
        lineEdit_SegmentationCylider_Distancethreshold->setText(QApplication::translate("PCLVisualizerClass", "0.05", 0));
        buttonpsegmentation_2->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        lineEdit_SegmentationCylider_MaxIterations_2->setText(QApplication::translate("PCLVisualizerClass", "10000", 0));
        lineEdit_SegmentationCylider_Radiuslimits->setText(QApplication::translate("PCLVisualizerClass", "0.1", 0));
        label_Greedy_Maxnear_6->setText(QApplication::translate("PCLVisualizerClass", "Radius_limits", 0));
        toolBox->setItemText(toolBox->indexOf(page_5), QApplication::translate("PCLVisualizerClass", "Cylider Segmentation", 0));
        groupBox_14->setTitle(QApplication::translate("PCLVisualizerClass", "NDT", 0));
        buttonndt->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        groupBox_15->setTitle(QApplication::translate("PCLVisualizerClass", "NDT set", 0));
        lineEdit_NormalDisTrans_Stepsize->setText(QApplication::translate("PCLVisualizerClass", "0.1", 0));
        label_Greedy_Maxnear_9->setText(QApplication::translate("PCLVisualizerClass", "Grid Resolution:", 0));
        lineEdit_NormalDisTrans_Maxiterations->setText(QApplication::translate("PCLVisualizerClass", "35", 0));
        label_Greedy_Maxnear_8->setText(QApplication::translate("PCLVisualizerClass", "Step size:", 0));
        lineEdit_NormalDisTrans_Gridresolution->setText(QApplication::translate("PCLVisualizerClass", "1.0", 0));
        label_Greedy_Maxnear_10->setText(QApplication::translate("PCLVisualizerClass", "Max Iterations:", 0));
        lineEdit_NormalDisTrans_Transepsilon->setText(QApplication::translate("PCLVisualizerClass", "0.01", 0));
        label_Greedy_Maxnear_7->setText(QApplication::translate("PCLVisualizerClass", "Trans Epsilon:", 0));
        groupBox_16->setTitle(QApplication::translate("PCLVisualizerClass", "VoxelGrid", 0));
        lineEdit_VoxelGridNDT_X->setText(QApplication::translate("PCLVisualizerClass", "0.5", 0));
        lineEdit_VoxelGridNDT_X->setPlaceholderText(QString());
        label_setLeafSize_Z_2->setText(QApplication::translate("PCLVisualizerClass", "setLeafSize_Z:", 0));
        label_setLeafSize_Y_2->setText(QApplication::translate("PCLVisualizerClass", "setLeafSize_Y:", 0));
        label_setLeafSize_X_2->setText(QApplication::translate("PCLVisualizerClass", "setLeafSize_X:", 0));
        lineEdit_VoxelGridNDT_Y->setText(QApplication::translate("PCLVisualizerClass", "0.5", 0));
        lineEdit_VoxelGridNDT_Y->setPlaceholderText(QString());
        lineEdit_VoxelGridNDT_Z->setText(QApplication::translate("PCLVisualizerClass", "0.5", 0));
        lineEdit_VoxelGridNDT_Z->setPlaceholderText(QString());
        toolBox->setItemText(toolBox->indexOf(page_7), QApplication::translate("PCLVisualizerClass", "Normal Distributions Trans", 0));
        groupBox_13->setTitle(QApplication::translate("PCLVisualizerClass", "ICP", 0));
        label_Greedy_Maxnear_11->setText(QApplication::translate("PCLVisualizerClass", "Max Iterations:", 0));
        lineEdit_ICP_Maxiterations->setText(QApplication::translate("PCLVisualizerClass", "5", 0));
        buttonicp->setText(QApplication::translate("PCLVisualizerClass", "DO!", 0));
        label_Greedy_Maxnear_12->setText(QApplication::translate("PCLVisualizerClass", "Trans Epsilon:", 0));
        lineEdit_ICP_Epsilon->setText(QApplication::translate("PCLVisualizerClass", "0.01", 0));
        toolBox->setItemText(toolBox->indexOf(page_6), QApplication::translate("PCLVisualizerClass", "Iterative Closest Point", 0));
        label_8->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class PCLVisualizerClass: public Ui_PCLVisualizerClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PCLVISUALIZER_H
